// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const datasourceUrl = process.env["DATABASE_URL"]?.trim();

if (!datasourceUrl) {
  throw new Error(
    "Defina DATABASE_URL (file:...) para executar comandos do Prisma CLI.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: datasourceUrl,
  },
});
